# Use distribution Ubuntu 18.04 Bionic
dist: bionic

# Use python build environment.
language: python

python:
    - "3.7"

# Handle dependencies in separate directory.
before_install:
    - DEPS_DIR="${HOME}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

# Install necessary packages.
install:
    # Install a recent version of CMake
    - |
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        if [ ! -f ${DEPS_DIR}/cmake/bin/cmake ] ; then mkdir -p cmake ; travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake ; fi
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Install a recent version of the Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then mkdir -p protobuf ; travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf ; cd protobuf ; ./configure --prefix=${DEPS_DIR}/protobuf/install ; make ; make install ; fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}
    
    - git clone https://github.com/OpenSimulationInterface/osi-validation.git
    - cd osi-validation
    - git checkout development
    - sudo python setup.py install
    - git clone https://github.com/OpenSimulationInterface/open-simulation-interface.git
    - git clone https://github.com/OpenSimulationInterface/proto2cpp.git
    - which python
    - cd open-simulation-interface 
    - pip install .
    - cd ..
    - pip install -r requirements.txt
    - pip install .
    - cp -R requirements-osi-3 vpython/lib/python3.6/site-packages/
  
# Addons necessary for documentation.
addons:
    apt:
        packages:
            - python3-pip
        

# Change directory back to default build directory.
before_script:
    - cd "${TRAVIS_BUILD_DIR}"

# Run the build script and generate documentation.
script:
    - cd osi-validation
    - python -m unittest discover tests
    - osi-validator/vpython/bin/python __main__.py
    - osivalidator

# Deploy the documentation on github (only for master branch).
# deploy:
#     provider: pages
#     skip_cleanup: true
#     local_dir: doc/html
#     keep-history: true
#     github_token: ${GH_REPO_TOKEN}
#     on: 
#         branch: master 